/*
# eBay Motors Integration — Listings + Config

1. New Tables
- `ebay_config` — singleton config row (id=1) storing eBay API credentials
  - `id` integer primary key default 1
  - `client_id` (text, nullable) — eBay developer client ID
  - `client_secret` (text, nullable) — eBay developer client secret (stored server-side only)
  - `ru_name` (text, nullable) — eBay Redirect URI name for OAuth
  - `environment` (text, default 'sandbox') — 'sandbox' or 'production'
  - `refresh_token` (text, nullable) — eBay OAuth refresh token (stored server-side only)
  - `user_token` (text, nullable) — eBay user access token (stored server-side, refreshed as needed)
  - `token_expires_at` (timestamptz, nullable) — when the user token expires
  - `merchant_name` (text, default 'Fort Peck Auto') — seller display name
  - `default_handling_time` (integer, default 2) — default handling time in days
  - `default_return_policy` (text, default 'ReturnsNotAccepted') — default return policy
  - `auto_publish` (boolean, default false) — auto-publish listings when created
  - `created_at` timestamptz default now()
  - `updated_at` timestamptz default now()

- `ebay_listings` — one row per part listed on eBay
  - `id` uuid primary key default gen_random_uuid()
  - `part_id` (text, NOT NULL) — matches the in-memory part ID (e.g. "uuid-p0")
  - `vehicle_id` (uuid, NOT NULL) — references vehicles.id
  - `ebay_item_id` (text, nullable) — eBay's item ID once published
  - `title` (text, NOT NULL) — listing title
  - `subtitle` (text, nullable)
  - `description` (text, nullable) — listing description
  - `category_id` (text, nullable) — eBay Motors category ID
  - `condition_id` (text, nullable) — eBay condition ID (e.g. '3000' for Used)
  - `condition_description` (text, nullable)
  - `price` numeric NOT NULL default 0
  - `quantity` integer NOT NULL default 1
  - `listing_status` text NOT NULL default 'draft' — 'draft', 'active', 'ended', 'sold', 'unsold'
  - `listing_duration` text NOT NULL default 'GTC' — GTC (Good Till Cancelled), Days_7, etc.
  - `start_price` numeric nullable — for auction listings
  - `buy_it_now_price` numeric nullable
  - `listing_type` text NOT NULL default 'FixedPrice' — 'FixedPrice' or 'Auction'
  - `shipping_weight_lbs` numeric nullable
  - `shipping_dimensions` jsonb nullable — {length, width, height, unit}
  - `shipping_cost` numeric default 0
  - `shipping_type` text default 'Flat' — 'Flat', 'Calculated', 'Free'
  - `payment_methods` jsonb default '[]' — array of accepted payment methods
  - `item_specifics` jsonb default '{}' — eBay item specifics (brand, OEM number, etc.)
  - `photo_urls` jsonb default '[]' — array of photo URLs
  - `view_count` integer default 0
  - `watch_count` integer default 0
  - `sold_at` timestamptz nullable
  - `ended_at` timestamptz nullable
  - `created_at` timestamptz default now()
  - `updated_at` timestamptz default now()

2. Security
- RLS enabled on both tables.
- Policies: anon + authenticated full CRUD (single-tenant app, shared data).
- `ebay_config.client_secret` and `ebay_config.refresh_token` are never exposed to the frontend — the edge function only selects public fields.

3. Important Notes
- Parts are in-memory (generated by generateDismantleParts). Part IDs are stable text strings like "<vehicleUuid>-p0".
- The ebay_listings.part_id column references these in-memory part IDs, not a separate parts table.
- When a listing sells on eBay, the part status is updated to 'sold' and an order is created in the existing orders table.
- The edge function handles eBay API communication (OAuth, publish, sync) — secrets never reach the browser.
*/
